# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/core/RoveControl.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'proto/core/RoveControl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.core import Orientation_pb2 as proto_dot_core_dot_Orientation__pb2
from proto.core import Vector3_pb2 as proto_dot_core_dot_Vector3__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/core/RoveControl.proto\x12\ttelemetry\x1a\x1cproto/core/Orientation.proto\x1a\x18proto/core/Vector3.proto\"\xb1\x01\n\x0bRoveControl\x12!\n\x06tracks\x18\x01 \x01(\x0b\x32\x11.telemetry.Tracks\x12%\n\x08\x66lippers\x18\x02 \x01(\x0b\x32\x13.telemetry.Flippers\x12\x1d\n\x04ovis\x18\x03 \x01(\x0b\x32\x0f.telemetry.Ovis\x12#\n\x07gripper\x18\x04 \x01(\x0b\x32\x12.telemetry.Gripper\x12\x14\n\x0ctimestamp_us\x18\x05 \x01(\x04\"-\n\x06Tracks\x12\x10\n\x08left_vel\x18\x01 \x01(\x02\x12\x11\n\tright_vel\x18\x02 \x01(\x02\":\n\x08\x46lippers\x12\n\n\x02\x66l\x18\x01 \x01(\x11\x12\n\n\x02\x66r\x18\x02 \x01(\x11\x12\n\n\x02rl\x18\x03 \x01(\x11\x12\n\n\x02rr\x18\x04 \x01(\x11\"Y\n\x04Ovis\x12+\n\x0borientation\x18\x01 \x01(\x0b\x32\x16.telemetry.Orientation\x12$\n\x08position\x18\x02 \x01(\x0b\x32\x12.telemetry.Vector3\"\x1b\n\x07Gripper\x12\x10\n\x08position\x18\x01 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.core.RoveControl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROVECONTROL']._serialized_start=100
  _globals['_ROVECONTROL']._serialized_end=277
  _globals['_TRACKS']._serialized_start=279
  _globals['_TRACKS']._serialized_end=324
  _globals['_FLIPPERS']._serialized_start=326
  _globals['_FLIPPERS']._serialized_end=384
  _globals['_OVIS']._serialized_start=386
  _globals['_OVIS']._serialized_end=475
  _globals['_GRIPPER']._serialized_start=477
  _globals['_GRIPPER']._serialized_end=504
# @@protoc_insertion_point(module_scope)
