# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/core/RoveTelemetry.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'proto/core/RoveTelemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.core import DriveNodeState_pb2 as proto_dot_core_dot_DriveNodeState__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eproto/core/RoveTelemetry.proto\x12\ttelemetry\x1a\x1fproto/core/DriveNodeState.proto\"d\n\rRoveTelemetry\x12&\n\x04ovis\x18\x02 \x01(\x0b\x32\x18.telemetry.OvisTelemetry\x12\x14\n\x0ctimestamp_us\x18\x05 \x01(\x04\x12\x15\n\rmachine_state\x18\x06 \x01(\r\"\x8b\x02\n\rOvisTelemetry\x12(\n\x05\x61\x63t_1\x18\x01 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12(\n\x05\x61\x63t_2\x18\x02 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12(\n\x05\x61\x63t_3\x18\x03 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12(\n\x05\x61\x63t_4\x18\x04 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12(\n\x05\x61\x63t_5\x18\x05 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12(\n\x05\x61\x63t_6\x18\x06 \x01(\x0b\x32\x19.telemetry.DriveNodeStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.core.RoveTelemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROVETELEMETRY']._serialized_start=78
  _globals['_ROVETELEMETRY']._serialized_end=178
  _globals['_OVISTELEMETRY']._serialized_start=181
  _globals['_OVISTELEMETRY']._serialized_end=448
# @@protoc_insertion_point(module_scope)
