# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/DriveNodeState.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/DriveNodeState.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.core import JointState_pb2 as proto_dot_core_dot_JointState__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/DriveNodeState.proto\x12\ttelemetry\x1a\x1bproto/core/JointState.proto\"\xb5\x01\n\x0e\x44riveNodeState\x12\x0f\n\x07node_id\x18\x01 \x01(\r\x12\x12\n\nnode_state\x18\x02 \x01(\r\x12\x13\n\x0bnode_temp_c\x18\x03 \x01(\x02\x12\x14\n\x0cmotor_temp_c\x18\x04 \x01(\x02\x12\x11\n\tmotor_amp\x18\x05 \x01(\x02\x12\x15\n\ractive_errors\x18\x06 \x01(\x05\x12\x16\n\x0elatched_errors\x18\x07 \x01(\x05\x12\x11\n\tmotor_pos\x18\x08 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.DriveNodeState_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRIVENODESTATE']._serialized_start=71
  _globals['_DRIVENODESTATE']._serialized_end=252
# @@protoc_insertion_point(module_scope)
