# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/RoveTelemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/RoveTelemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import Battery_pb2 as proto_dot_Battery__pb2
from proto import DriveNodeState_pb2 as proto_dot_DriveNodeState__pb2
from proto.imu import Icm40609_pb2 as proto_dot_imu_dot_Icm40609__pb2
from proto.imu import Vn300_pb2 as proto_dot_imu_dot_Vn300__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/RoveTelemetry.proto\x12\ttelemetry\x1a\x13proto/Battery.proto\x1a\x1aproto/DriveNodeState.proto\x1a\x18proto/imu/Icm40609.proto\x1a\x15proto/imu/Vn300.proto\"\xc1\x01\n\rRoveTelemetry\x12,\n\x07odrives\x18\x01 \x01(\x0b\x32\x1b.telemetry.OdrivesTelemetry\x12&\n\x04ovis\x18\x02 \x01(\x0b\x32\x18.telemetry.OvisTelemetry\x12\x1f\n\x05vn300\x18\x03 \x01(\x0b\x32\x10.telemetry.Vn300\x12#\n\x07\x62\x61ttery\x18\x04 \x01(\x0b\x32\x12.telemetry.Battery\x12\x14\n\x0ctimestamp_us\x18\x05 \x01(\x04\"\xea\x02\n\x10OdrivesTelemetry\x12)\n\x06node_1\x18\x01 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12)\n\x06node_2\x18\x02 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12)\n\x06node_3\x18\x03 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12)\n\x06node_4\x18\x04 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12)\n\x06node_5\x18\x05 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12)\n\x06node_6\x18\x06 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12)\n\x06node_7\x18\x07 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12)\n\x06node_8\x18\x08 \x01(\x0b\x32\x19.telemetry.DriveNodeState\"\x8b\x02\n\rOvisTelemetry\x12(\n\x05\x61\x63t_1\x18\x01 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12(\n\x05\x61\x63t_2\x18\x02 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12(\n\x05\x61\x63t_3\x18\x03 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12(\n\x05\x61\x63t_4\x18\x04 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12(\n\x05\x61\x63t_5\x18\x05 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12(\n\x05\x61\x63t_6\x18\x06 \x01(\x0b\x32\x19.telemetry.DriveNodeStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.RoveTelemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROVETELEMETRY']._serialized_start=139
  _globals['_ROVETELEMETRY']._serialized_end=332
  _globals['_ODRIVESTELEMETRY']._serialized_start=335
  _globals['_ODRIVESTELEMETRY']._serialized_end=697
  _globals['_OVISTELEMETRY']._serialized_start=700
  _globals['_OVISTELEMETRY']._serialized_end=967
# @@protoc_insertion_point(module_scope)
