# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/imu/Icm40609.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.core import Vector3_pb2 as proto_dot_core_dot_Vector3__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/imu/Icm40609.proto',
  package='telemetry',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18proto/imu/Icm40609.proto\x12\ttelemetry\x1a\x18proto/core/Vector3.proto\"_\n\x08Icm40609\x12!\n\x05\x61\x63\x63\x65l\x18\x01 \x01(\x0b\x32\x12.telemetry.Vector3\x12 \n\x04gyro\x18\x02 \x01(\x0b\x32\x12.telemetry.Vector3\x12\x0e\n\x06temp_c\x18\x03 \x01(\x02\x62\x06proto3'
  ,
  dependencies=[proto_dot_core_dot_Vector3__pb2.DESCRIPTOR,])




_ICM40609 = _descriptor.Descriptor(
  name='Icm40609',
  full_name='telemetry.Icm40609',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accel', full_name='telemetry.Icm40609.accel', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gyro', full_name='telemetry.Icm40609.gyro', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temp_c', full_name='telemetry.Icm40609.temp_c', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=160,
)

_ICM40609.fields_by_name['accel'].message_type = proto_dot_core_dot_Vector3__pb2._VECTOR3
_ICM40609.fields_by_name['gyro'].message_type = proto_dot_core_dot_Vector3__pb2._VECTOR3
DESCRIPTOR.message_types_by_name['Icm40609'] = _ICM40609
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Icm40609 = _reflection.GeneratedProtocolMessageType('Icm40609', (_message.Message,), {
  'DESCRIPTOR' : _ICM40609,
  '__module__' : 'proto.imu.Icm40609_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.Icm40609)
  })
_sym_db.RegisterMessage(Icm40609)


# @@protoc_insertion_point(module_scope)
