# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/imu/Vn300.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.core import Orientation_pb2 as proto_dot_core_dot_Orientation__pb2
from proto.core import Position_pb2 as proto_dot_core_dot_Position__pb2
from proto.core import Vector3_pb2 as proto_dot_core_dot_Vector3__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/imu/Vn300.proto',
  package='telemetry',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15proto/imu/Vn300.proto\x12\ttelemetry\x1a\x1cproto/core/Orientation.proto\x1a\x19proto/core/Position.proto\x1a\x18proto/core/Vector3.proto\"\xc6\x01\n\x05Vn300\x12%\n\x08position\x18\x01 \x01(\x0b\x32\x13.telemetry.Position\x12+\n\x0borientation\x18\x02 \x01(\x0b\x32\x16.telemetry.Orientation\x12$\n\x08velocity\x18\x03 \x01(\x0b\x32\x12.telemetry.Vector3\x12!\n\x05\x61\x63\x63\x65l\x18\x04 \x01(\x0b\x32\x12.telemetry.Vector3\x12 \n\x04gyro\x18\x05 \x01(\x0b\x32\x12.telemetry.Vector3b\x06proto3'
  ,
  dependencies=[proto_dot_core_dot_Orientation__pb2.DESCRIPTOR,proto_dot_core_dot_Position__pb2.DESCRIPTOR,proto_dot_core_dot_Vector3__pb2.DESCRIPTOR,])




_VN300 = _descriptor.Descriptor(
  name='Vn300',
  full_name='telemetry.Vn300',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='telemetry.Vn300.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='telemetry.Vn300.orientation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='telemetry.Vn300.velocity', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accel', full_name='telemetry.Vn300.accel', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gyro', full_name='telemetry.Vn300.gyro', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=318,
)

_VN300.fields_by_name['position'].message_type = proto_dot_core_dot_Position__pb2._POSITION
_VN300.fields_by_name['orientation'].message_type = proto_dot_core_dot_Orientation__pb2._ORIENTATION
_VN300.fields_by_name['velocity'].message_type = proto_dot_core_dot_Vector3__pb2._VECTOR3
_VN300.fields_by_name['accel'].message_type = proto_dot_core_dot_Vector3__pb2._VECTOR3
_VN300.fields_by_name['gyro'].message_type = proto_dot_core_dot_Vector3__pb2._VECTOR3
DESCRIPTOR.message_types_by_name['Vn300'] = _VN300
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vn300 = _reflection.GeneratedProtocolMessageType('Vn300', (_message.Message,), {
  'DESCRIPTOR' : _VN300,
  '__module__' : 'proto.imu.Vn300_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.Vn300)
  })
_sym_db.RegisterMessage(Vn300)


# @@protoc_insertion_point(module_scope)
