# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/DriveNodeState.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.core import JointState_pb2 as proto_dot_core_dot_JointState__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/DriveNodeState.proto',
  package='telemetry',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aproto/DriveNodeState.proto\x12\ttelemetry\x1a\x1bproto/core/JointState.proto\"\xb5\x01\n\x0e\x44riveNodeState\x12\x0f\n\x07node_id\x18\x01 \x01(\r\x12\x12\n\nnode_state\x18\x02 \x01(\r\x12\x13\n\x0bnode_temp_c\x18\x03 \x01(\x02\x12\x14\n\x0cmotor_temp_c\x18\x04 \x01(\x02\x12\x11\n\tmotor_amp\x18\x05 \x01(\x02\x12\x15\n\ractive_errors\x18\x06 \x01(\x05\x12\x16\n\x0elatched_errors\x18\x07 \x01(\x05\x12\x11\n\tmotor_pos\x18\x08 \x01(\x02\x62\x06proto3'
  ,
  dependencies=[proto_dot_core_dot_JointState__pb2.DESCRIPTOR,])




_DRIVENODESTATE = _descriptor.Descriptor(
  name='DriveNodeState',
  full_name='telemetry.DriveNodeState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='telemetry.DriveNodeState.node_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_state', full_name='telemetry.DriveNodeState.node_state', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_temp_c', full_name='telemetry.DriveNodeState.node_temp_c', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_temp_c', full_name='telemetry.DriveNodeState.motor_temp_c', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_amp', full_name='telemetry.DriveNodeState.motor_amp', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='active_errors', full_name='telemetry.DriveNodeState.active_errors', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latched_errors', full_name='telemetry.DriveNodeState.latched_errors', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_pos', full_name='telemetry.DriveNodeState.motor_pos', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=252,
)

DESCRIPTOR.message_types_by_name['DriveNodeState'] = _DRIVENODESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DriveNodeState = _reflection.GeneratedProtocolMessageType('DriveNodeState', (_message.Message,), {
  'DESCRIPTOR' : _DRIVENODESTATE,
  '__module__' : 'proto.DriveNodeState_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.DriveNodeState)
  })
_sym_db.RegisterMessage(DriveNodeState)


# @@protoc_insertion_point(module_scope)
