# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/RoveTelemetry.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import Battery_pb2 as proto_dot_Battery__pb2
from proto import DriveNodeState_pb2 as proto_dot_DriveNodeState__pb2
from proto.imu import Icm40609_pb2 as proto_dot_imu_dot_Icm40609__pb2
from proto.imu import Vn300_pb2 as proto_dot_imu_dot_Vn300__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/RoveTelemetry.proto',
  package='telemetry',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19proto/RoveTelemetry.proto\x12\ttelemetry\x1a\x13proto/Battery.proto\x1a\x1aproto/DriveNodeState.proto\x1a\x18proto/imu/Icm40609.proto\x1a\x15proto/imu/Vn300.proto\"\xc1\x01\n\rRoveTelemetry\x12,\n\x07odrives\x18\x01 \x01(\x0b\x32\x1b.telemetry.OdrivesTelemetry\x12&\n\x04ovis\x18\x02 \x01(\x0b\x32\x18.telemetry.OvisTelemetry\x12\x1f\n\x05vn300\x18\x03 \x01(\x0b\x32\x10.telemetry.Vn300\x12#\n\x07\x62\x61ttery\x18\x04 \x01(\x0b\x32\x12.telemetry.Battery\x12\x14\n\x0ctimestamp_us\x18\x05 \x01(\x04\"\xea\x02\n\x10OdrivesTelemetry\x12)\n\x06node_1\x18\x01 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12)\n\x06node_2\x18\x02 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12)\n\x06node_3\x18\x03 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12)\n\x06node_4\x18\x04 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12)\n\x06node_5\x18\x05 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12)\n\x06node_6\x18\x06 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12)\n\x06node_7\x18\x07 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12)\n\x06node_8\x18\x08 \x01(\x0b\x32\x19.telemetry.DriveNodeState\"\x8b\x02\n\rOvisTelemetry\x12(\n\x05\x61\x63t_1\x18\x01 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12(\n\x05\x61\x63t_2\x18\x02 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12(\n\x05\x61\x63t_3\x18\x03 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12(\n\x05\x61\x63t_4\x18\x04 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12(\n\x05\x61\x63t_5\x18\x05 \x01(\x0b\x32\x19.telemetry.DriveNodeState\x12(\n\x05\x61\x63t_6\x18\x06 \x01(\x0b\x32\x19.telemetry.DriveNodeStateb\x06proto3'
  ,
  dependencies=[proto_dot_Battery__pb2.DESCRIPTOR,proto_dot_DriveNodeState__pb2.DESCRIPTOR,proto_dot_imu_dot_Icm40609__pb2.DESCRIPTOR,proto_dot_imu_dot_Vn300__pb2.DESCRIPTOR,])




_ROVETELEMETRY = _descriptor.Descriptor(
  name='RoveTelemetry',
  full_name='telemetry.RoveTelemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='odrives', full_name='telemetry.RoveTelemetry.odrives', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ovis', full_name='telemetry.RoveTelemetry.ovis', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vn300', full_name='telemetry.RoveTelemetry.vn300', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='battery', full_name='telemetry.RoveTelemetry.battery', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp_us', full_name='telemetry.RoveTelemetry.timestamp_us', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=332,
)


_ODRIVESTELEMETRY = _descriptor.Descriptor(
  name='OdrivesTelemetry',
  full_name='telemetry.OdrivesTelemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_1', full_name='telemetry.OdrivesTelemetry.node_1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_2', full_name='telemetry.OdrivesTelemetry.node_2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_3', full_name='telemetry.OdrivesTelemetry.node_3', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_4', full_name='telemetry.OdrivesTelemetry.node_4', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_5', full_name='telemetry.OdrivesTelemetry.node_5', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_6', full_name='telemetry.OdrivesTelemetry.node_6', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_7', full_name='telemetry.OdrivesTelemetry.node_7', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_8', full_name='telemetry.OdrivesTelemetry.node_8', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=697,
)


_OVISTELEMETRY = _descriptor.Descriptor(
  name='OvisTelemetry',
  full_name='telemetry.OvisTelemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='act_1', full_name='telemetry.OvisTelemetry.act_1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='act_2', full_name='telemetry.OvisTelemetry.act_2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='act_3', full_name='telemetry.OvisTelemetry.act_3', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='act_4', full_name='telemetry.OvisTelemetry.act_4', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='act_5', full_name='telemetry.OvisTelemetry.act_5', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='act_6', full_name='telemetry.OvisTelemetry.act_6', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=700,
  serialized_end=967,
)

_ROVETELEMETRY.fields_by_name['odrives'].message_type = _ODRIVESTELEMETRY
_ROVETELEMETRY.fields_by_name['ovis'].message_type = _OVISTELEMETRY
_ROVETELEMETRY.fields_by_name['vn300'].message_type = proto_dot_imu_dot_Vn300__pb2._VN300
_ROVETELEMETRY.fields_by_name['battery'].message_type = proto_dot_Battery__pb2._BATTERY
_ODRIVESTELEMETRY.fields_by_name['node_1'].message_type = proto_dot_DriveNodeState__pb2._DRIVENODESTATE
_ODRIVESTELEMETRY.fields_by_name['node_2'].message_type = proto_dot_DriveNodeState__pb2._DRIVENODESTATE
_ODRIVESTELEMETRY.fields_by_name['node_3'].message_type = proto_dot_DriveNodeState__pb2._DRIVENODESTATE
_ODRIVESTELEMETRY.fields_by_name['node_4'].message_type = proto_dot_DriveNodeState__pb2._DRIVENODESTATE
_ODRIVESTELEMETRY.fields_by_name['node_5'].message_type = proto_dot_DriveNodeState__pb2._DRIVENODESTATE
_ODRIVESTELEMETRY.fields_by_name['node_6'].message_type = proto_dot_DriveNodeState__pb2._DRIVENODESTATE
_ODRIVESTELEMETRY.fields_by_name['node_7'].message_type = proto_dot_DriveNodeState__pb2._DRIVENODESTATE
_ODRIVESTELEMETRY.fields_by_name['node_8'].message_type = proto_dot_DriveNodeState__pb2._DRIVENODESTATE
_OVISTELEMETRY.fields_by_name['act_1'].message_type = proto_dot_DriveNodeState__pb2._DRIVENODESTATE
_OVISTELEMETRY.fields_by_name['act_2'].message_type = proto_dot_DriveNodeState__pb2._DRIVENODESTATE
_OVISTELEMETRY.fields_by_name['act_3'].message_type = proto_dot_DriveNodeState__pb2._DRIVENODESTATE
_OVISTELEMETRY.fields_by_name['act_4'].message_type = proto_dot_DriveNodeState__pb2._DRIVENODESTATE
_OVISTELEMETRY.fields_by_name['act_5'].message_type = proto_dot_DriveNodeState__pb2._DRIVENODESTATE
_OVISTELEMETRY.fields_by_name['act_6'].message_type = proto_dot_DriveNodeState__pb2._DRIVENODESTATE
DESCRIPTOR.message_types_by_name['RoveTelemetry'] = _ROVETELEMETRY
DESCRIPTOR.message_types_by_name['OdrivesTelemetry'] = _ODRIVESTELEMETRY
DESCRIPTOR.message_types_by_name['OvisTelemetry'] = _OVISTELEMETRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RoveTelemetry = _reflection.GeneratedProtocolMessageType('RoveTelemetry', (_message.Message,), {
  'DESCRIPTOR' : _ROVETELEMETRY,
  '__module__' : 'proto.RoveTelemetry_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.RoveTelemetry)
  })
_sym_db.RegisterMessage(RoveTelemetry)

OdrivesTelemetry = _reflection.GeneratedProtocolMessageType('OdrivesTelemetry', (_message.Message,), {
  'DESCRIPTOR' : _ODRIVESTELEMETRY,
  '__module__' : 'proto.RoveTelemetry_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.OdrivesTelemetry)
  })
_sym_db.RegisterMessage(OdrivesTelemetry)

OvisTelemetry = _reflection.GeneratedProtocolMessageType('OvisTelemetry', (_message.Message,), {
  'DESCRIPTOR' : _OVISTELEMETRY,
  '__module__' : 'proto.RoveTelemetry_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.OvisTelemetry)
  })
_sym_db.RegisterMessage(OvisTelemetry)


# @@protoc_insertion_point(module_scope)
