# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/RoveControl.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.core import JointState_pb2 as proto_dot_core_dot_JointState__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/RoveControl.proto',
  package='telemetry',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17proto/RoveControl.proto\x12\ttelemetry\x1a\x1bproto/core/JointState.proto\"\x8c\x01\n\x0bRoveControl\x12!\n\x06tracks\x18\x01 \x01(\x0b\x32\x11.telemetry.Tracks\x12%\n\x08\x66lippers\x18\x02 \x01(\x0b\x32\x13.telemetry.Flippers\x12\x1d\n\x04ovis\x18\x03 \x01(\x0b\x32\x0f.telemetry.Ovis\x12\x14\n\x0ctimestamp_us\x18\x04 \x01(\x04\"-\n\x06Tracks\x12\x10\n\x08left_vel\x18\x01 \x01(\x02\x12\x11\n\tright_vel\x18\x02 \x01(\x02\"\x96\x01\n\x08\x46lippers\x12!\n\x02\x66l\x18\x01 \x01(\x0b\x32\x15.telemetry.JointState\x12!\n\x02\x66r\x18\x02 \x01(\x0b\x32\x15.telemetry.JointState\x12!\n\x02rl\x18\x03 \x01(\x0b\x32\x15.telemetry.JointState\x12!\n\x02rr\x18\x04 \x01(\x0b\x32\x15.telemetry.JointState\"\xea\x01\n\x04Ovis\x12$\n\x05\x61\x63t_1\x18\x01 \x01(\x0b\x32\x15.telemetry.JointState\x12$\n\x05\x61\x63t_2\x18\x02 \x01(\x0b\x32\x15.telemetry.JointState\x12$\n\x05\x61\x63t_3\x18\x03 \x01(\x0b\x32\x15.telemetry.JointState\x12$\n\x05\x61\x63t_4\x18\x04 \x01(\x0b\x32\x15.telemetry.JointState\x12$\n\x05\x61\x63t_5\x18\x05 \x01(\x0b\x32\x15.telemetry.JointState\x12$\n\x05\x61\x63t_6\x18\x06 \x01(\x0b\x32\x15.telemetry.JointStateb\x06proto3'
  ,
  dependencies=[proto_dot_core_dot_JointState__pb2.DESCRIPTOR,])




_ROVECONTROL = _descriptor.Descriptor(
  name='RoveControl',
  full_name='telemetry.RoveControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tracks', full_name='telemetry.RoveControl.tracks', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flippers', full_name='telemetry.RoveControl.flippers', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ovis', full_name='telemetry.RoveControl.ovis', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp_us', full_name='telemetry.RoveControl.timestamp_us', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=208,
)


_TRACKS = _descriptor.Descriptor(
  name='Tracks',
  full_name='telemetry.Tracks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='left_vel', full_name='telemetry.Tracks.left_vel', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right_vel', full_name='telemetry.Tracks.right_vel', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=255,
)


_FLIPPERS = _descriptor.Descriptor(
  name='Flippers',
  full_name='telemetry.Flippers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fl', full_name='telemetry.Flippers.fl', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fr', full_name='telemetry.Flippers.fr', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rl', full_name='telemetry.Flippers.rl', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rr', full_name='telemetry.Flippers.rr', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=408,
)


_OVIS = _descriptor.Descriptor(
  name='Ovis',
  full_name='telemetry.Ovis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='act_1', full_name='telemetry.Ovis.act_1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='act_2', full_name='telemetry.Ovis.act_2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='act_3', full_name='telemetry.Ovis.act_3', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='act_4', full_name='telemetry.Ovis.act_4', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='act_5', full_name='telemetry.Ovis.act_5', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='act_6', full_name='telemetry.Ovis.act_6', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=411,
  serialized_end=645,
)

_ROVECONTROL.fields_by_name['tracks'].message_type = _TRACKS
_ROVECONTROL.fields_by_name['flippers'].message_type = _FLIPPERS
_ROVECONTROL.fields_by_name['ovis'].message_type = _OVIS
_FLIPPERS.fields_by_name['fl'].message_type = proto_dot_core_dot_JointState__pb2._JOINTSTATE
_FLIPPERS.fields_by_name['fr'].message_type = proto_dot_core_dot_JointState__pb2._JOINTSTATE
_FLIPPERS.fields_by_name['rl'].message_type = proto_dot_core_dot_JointState__pb2._JOINTSTATE
_FLIPPERS.fields_by_name['rr'].message_type = proto_dot_core_dot_JointState__pb2._JOINTSTATE
_OVIS.fields_by_name['act_1'].message_type = proto_dot_core_dot_JointState__pb2._JOINTSTATE
_OVIS.fields_by_name['act_2'].message_type = proto_dot_core_dot_JointState__pb2._JOINTSTATE
_OVIS.fields_by_name['act_3'].message_type = proto_dot_core_dot_JointState__pb2._JOINTSTATE
_OVIS.fields_by_name['act_4'].message_type = proto_dot_core_dot_JointState__pb2._JOINTSTATE
_OVIS.fields_by_name['act_5'].message_type = proto_dot_core_dot_JointState__pb2._JOINTSTATE
_OVIS.fields_by_name['act_6'].message_type = proto_dot_core_dot_JointState__pb2._JOINTSTATE
DESCRIPTOR.message_types_by_name['RoveControl'] = _ROVECONTROL
DESCRIPTOR.message_types_by_name['Tracks'] = _TRACKS
DESCRIPTOR.message_types_by_name['Flippers'] = _FLIPPERS
DESCRIPTOR.message_types_by_name['Ovis'] = _OVIS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RoveControl = _reflection.GeneratedProtocolMessageType('RoveControl', (_message.Message,), {
  'DESCRIPTOR' : _ROVECONTROL,
  '__module__' : 'proto.RoveControl_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.RoveControl)
  })
_sym_db.RegisterMessage(RoveControl)

Tracks = _reflection.GeneratedProtocolMessageType('Tracks', (_message.Message,), {
  'DESCRIPTOR' : _TRACKS,
  '__module__' : 'proto.RoveControl_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.Tracks)
  })
_sym_db.RegisterMessage(Tracks)

Flippers = _reflection.GeneratedProtocolMessageType('Flippers', (_message.Message,), {
  'DESCRIPTOR' : _FLIPPERS,
  '__module__' : 'proto.RoveControl_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.Flippers)
  })
_sym_db.RegisterMessage(Flippers)

Ovis = _reflection.GeneratedProtocolMessageType('Ovis', (_message.Message,), {
  'DESCRIPTOR' : _OVIS,
  '__module__' : 'proto.RoveControl_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.Ovis)
  })
_sym_db.RegisterMessage(Ovis)


# @@protoc_insertion_point(module_scope)
