# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/imu/Vn300.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/imu/Vn300.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.core import Orientation_pb2 as proto_dot_core_dot_Orientation__pb2
from proto.core import Position_pb2 as proto_dot_core_dot_Position__pb2
from proto.core import Vector3_pb2 as proto_dot_core_dot_Vector3__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/imu/Vn300.proto\x12\ttelemetry\x1a\x1cproto/core/Orientation.proto\x1a\x19proto/core/Position.proto\x1a\x18proto/core/Vector3.proto\"\xc6\x01\n\x05Vn300\x12%\n\x08position\x18\x01 \x01(\x0b\x32\x13.telemetry.Position\x12+\n\x0borientation\x18\x02 \x01(\x0b\x32\x16.telemetry.Orientation\x12$\n\x08velocity\x18\x03 \x01(\x0b\x32\x12.telemetry.Vector3\x12!\n\x05\x61\x63\x63\x65l\x18\x04 \x01(\x0b\x32\x12.telemetry.Vector3\x12 \n\x04gyro\x18\x05 \x01(\x0b\x32\x12.telemetry.Vector3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.imu.Vn300_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VN300']._serialized_start=120
  _globals['_VN300']._serialized_end=318
# @@protoc_insertion_point(module_scope)
